defaults: &defaults
  twitter:
    consumer_key: 'GvwdaKqJEz1GvPHajM3SZw'
    consumer_secret: 'bhlMUCQuhoXFF1UBusb4w0f3rMGNaGpm0Hy2yNC52w'
  bitly:
    user_id: 'o_1hd0dbq1kc'
    api_key: 'R_c9f24281925444ded9f72c8e6b1a97e5'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults