// Generated by CoffeeScript 1.3.3
(function() {
  var annot;

  annot = $(document.body).annotator();

  annot.annotator('addPlugin', 'Tags');

  annot.annotator('addPlugin', 'Store', {
    prefix: 'http://' + kurukuma.domain + '/messages',
    annotationData: {
      'uri': document.URL
    },
    loadFromSearch: {
      'limit': 20,
      'uri': document.URL
    }
  });

  annot.annotator('addPlugin', 'Twitter', {
    prefix: 'http://' + kurukuma.domain + '/'
  });

  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    return window.kurukuma_user_info = request.user_info;
  });

  chrome.extension.sendRequest({
    name: "kurukuma"
  });

}).call(this);
