// Generated by CoffeeScript 1.3.3
(function() {
  var request,
    _this = this;

  request = $.ajax('http://kurukuma.herokuapp.com/page/twitter_info', {
    type: "get",
    dataType: "json",
    success: function(data) {
      var back;
      console.log('ajax:twitter_info');
      console.log(data);
      if (data.redirect_url) {

      } else {
        back = chrome.extension.getBackgroundPage();
        return back.kurukuma_user_info = data.twitter_info.info;
      }
    }
  });

}).call(this);
